### PR TITLE
Validate lat/lng values

### PR DESCRIPTION
**Pull request by nfroidure**

### CODE REVIEW

**Comment by jfgodoy** [comment]
latitud range should be between -90 and 90

**Comment by nfroidure** [comment]
Alright! Updated.

**Comment by fge** [comment]
Hmm, it was my understanding that the coordinates system could vary?

**Comment by jfgodoy** [comment]
the `crs` property define the coordinate system. The default CRS is a geographic coordinate reference system, using the WGS84 datum, and with longitude and latitude units of decimal degrees. So this validation works only for the default case.

**Comment by fge** [comment]
OK, that's what i recall (gosh, it was long ago since I've written this schema), which is why I left the schema as imprecise as it is.

Transforming the schema to account for this would be possible but the end result would be quite awkward to read -- recall that JSON does not accept comment, although JSON Schema does accept object members not defined by JSON Schema itself.

Not sure what to do, really.

**Comment by nfroidure** [comment]
Best would probably be to make JSONSchema configurable per something like environment variables or so.

In my particular case, since JavaScript modules are the de facto standard, i use them to compose JSONSchema for a less verbose schema definition, it give things like this :

``` js
'use strict';

var schemaUtils = require('../utils/schema');

module.exports = {
  $schema: 'http://json-schema.org/draft-04/schema#',
  title: 'Location',
  type: 'object',
  additionalProperties: false,
  required: [
    'name', 'street', 'zipcode', 'city', 'country', 'organisation_id',
    'owner_id',
  ],
  properties: {
    name: {
      type: 'string',
    },
    street: {
      type: 'string',
    },
    zipcode: {
      type: 'string',
    },
    city: {
      type: 'string',
    },
    country: {
      type: 'string',
      default: 'France',
    },
    approximate: {
      type: 'boolean',
      default: false,
    },
    latLng: schemaUtils.latLng(),
    organisation_id: schemaUtils.oneToOne(),
    owner_id: schemaUtils.oneToOne(),
    chiefs_ids: schemaUtils.oneToSeveral(),
    users_ids: schemaUtils.oneToSeveral(),
    products_ids: schemaUtils.oneToSeveral(),
    groups: schemaUtils.groups(),
    params: schemaUtils.params(),
    tags: schemaUtils.tags(),
  },
};
```

The fact is the module return plain serializable JSON Schema, i see modules like sort of a macro language. It could apply to GeoJSON particular case in a way.

**Comment by nfroidure** [comment]
Closing to remove it from my PR list.

**Pull request closed without merging**
